-- ============================================================
-- validate_04_telecom_nexttrade.sql
-- 아정당 + NextTrade 뷰 6개 데이터 정합성 검증
-- 이슈: #19
-- ============================================================

-- 6개 뷰의 row count + 날짜 범위를 한번에 확인
SELECT 'V_TELECOM_NEW_INSTALL' AS view_name, COUNT(*) AS row_cnt,
       MIN(YEAR_MONTH) AS min_date, MAX(YEAR_MONTH) AS max_date
FROM MOVING_INTEL.ANALYTICS.V_TELECOM_NEW_INSTALL
UNION ALL
SELECT 'V_TELECOM_CONTRACT_STATS', COUNT(*),
       MIN(YEAR_MONTH), MAX(YEAR_MONTH)
FROM MOVING_INTEL.ANALYTICS.V_TELECOM_CONTRACT_STATS
UNION ALL
SELECT 'V_TELECOM_BUNDLE', COUNT(*),
       MIN(YEAR_MONTH), MAX(YEAR_MONTH)
FROM MOVING_INTEL.ANALYTICS.V_TELECOM_BUNDLE
UNION ALL
SELECT 'V_TELECOM_FUNNEL', COUNT(*),
       MIN(YEAR_MONTH), MAX(YEAR_MONTH)
FROM MOVING_INTEL.ANALYTICS.V_TELECOM_FUNNEL
UNION ALL
SELECT 'V_NEXTTRADE_REFER', COUNT(*),
       MIN(DWDD)::VARCHAR, MAX(DWDD)::VARCHAR
FROM MOVING_INTEL.ANALYTICS.V_NEXTTRADE_REFER
UNION ALL
SELECT 'V_NEXTTRADE_PRICE', COUNT(*),
       MIN(DWDD)::VARCHAR, MAX(DWDD)::VARCHAR
FROM MOVING_INTEL.ANALYTICS.V_NEXTTRADE_PRICE;

-- 기대 결과:
-- V_TELECOM_NEW_INSTALL    | > 0 | ...  | ...
-- V_TELECOM_CONTRACT_STATS | > 0 | ...  | ...
-- V_TELECOM_BUNDLE         | > 0 | ...  | ...
-- V_TELECOM_FUNNEL         | > 0 | ...  | ...
-- V_NEXTTRADE_REFER        | > 0 | ...  | ...
-- V_NEXTTRADE_PRICE        | > 0 | ...  | ...

-- V05 필수 컬럼 확인 (이사 시그널 핵심)
SELECT YEAR_MONTH, INSTALL_STATE, INSTALL_CITY,
       CONTRACT_COUNT, OPEN_COUNT, PAYEND_COUNT
FROM MOVING_INTEL.ANALYTICS.V_TELECOM_NEW_INSTALL LIMIT 1;

-- 기대 결과: 6개 컬럼 모두 존재

-- NextTrade 체결가 필수 컬럼 확인
SELECT DWDD, ISU_CD, TD_PRC, TRD_QTY, ACC_TRVAL
FROM MOVING_INTEL.ANALYTICS.V_NEXTTRADE_PRICE LIMIT 1;

-- 기대 결과: 5개 컬럼 존재
