-- ============================================================
-- 002_richgo_views.sql
-- RICHGO Marketplace 데이터 참조 뷰 3개 생성
-- 이슈: #17 (feat: RICHGO 참조 뷰 3개 생성)
-- 의존성: #16 (MOVING_INTEL.ANALYTICS 스키마)
-- 멱등성: CREATE OR REPLACE — 반복 실행 안전
-- ============================================================

-- Step 0: 컨텍스트 설정
USE WAREHOUSE MOVING_INTEL_WH;
USE SCHEMA MOVING_INTEL.ANALYTICS;

-- Step 1: V_RICHGO_MARKET_PRICE — 아파트 시세 (2012-01 ~ 2024-12, 4356건)
CREATE OR REPLACE VIEW V_RICHGO_MARKET_PRICE
  COMMENT = 'RICHGO 아파트 시세 월별 집계 (Marketplace 직접 참조)'
AS
SELECT
    REGION_LEVEL,
    BJD_CODE,       -- 법정동코드 10자리 (#20 V_BJD_DISTRICT_MAP 매핑 키)
    SD,             -- 시/도
    SGG,            -- 시/군/구
    EMD,            -- 읍/면/동
    YYYYMMDD,       -- DATE, 월별 집계 기준일
    TOTAL_HOUSEHOLDS,
    MEME_PRICE_PER_SUPPLY_PYEONG,
    JEONSE_PRICE_PER_SUPPLY_PYEONG
FROM KOREAN_POPULATION__APARTMENT_MARKET_PRICE_DATA.HACKATHON_2025Q2.REGION_APT_RICHGO_MARKET_PRICE_M_H;

-- Step 2: V_RICHGO_POPULATION — 인구 성별/연령 (2025-01, 118건)
CREATE OR REPLACE VIEW V_RICHGO_POPULATION
  COMMENT = 'RICHGO 인구 성별/연령별 스냅샷 (Marketplace 직접 참조)'
AS
SELECT
    BJD_CODE,
    SD, SGG, EMD,
    YYYYMMDD,
    TOTAL, MALE, FEMALE,
    AGE_UNDER20, AGE_20S, AGE_30S, AGE_40S, AGE_50S, AGE_60S, AGE_OVER70
FROM KOREAN_POPULATION__APARTMENT_MARKET_PRICE_DATA.HACKATHON_2025Q2.REGION_MOIS_POPULATION_GENDER_AGE_M_H;

-- Step 3: V_RICHGO_YOUNG_CHILDREN — 영유아/가임여성 비율 (2025-01, 118건)
CREATE OR REPLACE VIEW V_RICHGO_YOUNG_CHILDREN
  COMMENT = 'RICHGO 영유아 대비 가임여성 비율 (Marketplace 직접 참조)'
AS
SELECT
    BJD_CODE,
    SD, SGG, EMD,
    YYYYMMDD,
    AGE_UNDER5,
    FEMALE_20TO40,
    AGE_UNDER5_PER_FEMALE_20TO40
FROM KOREAN_POPULATION__APARTMENT_MARKET_PRICE_DATA.HACKATHON_2025Q2.REGION_MOIS_POPULATION_AGE_UNDER5_PER_FEMALE_20TO40_M_H;
