-- ============================================================
-- 003_sph_views.sql
-- SPH Marketplace 데이터 참조 뷰 4개 생성
-- 이슈: #18 (feat: SPH 참조 뷰 4개 생성)
-- 의존성: #16 (MOVING_INTEL.ANALYTICS 스키마)
-- 멱등성: CREATE OR REPLACE — 반복 실행 안전
-- ============================================================

-- Step 0: 컨텍스트 설정
USE WAREHOUSE MOVING_INTEL_WH;
USE SCHEMA MOVING_INTEL.ANALYTICS;

-- Step 1: V_SPH_FLOATING_POP — 유동인구 (2,577,120건)
CREATE OR REPLACE VIEW V_SPH_FLOATING_POP
  COMMENT = 'SPH 유동인구 (서울 25구 467동, Marketplace 직접 참조)'
AS
SELECT
    PROVINCE_CODE, CITY_CODE, DISTRICT_CODE, STANDARD_YEAR_MONTH,
    WEEKDAY_WEEKEND, GENDER, AGE_GROUP, TIME_SLOT,
    RESIDENTIAL_POPULATION, WORKING_POPULATION, VISITING_POPULATION
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.FLOATING_POPULATION_INFO;

-- Step 2: V_SPH_CARD_SALES — 카드매출 (6,208,957건)
CREATE OR REPLACE VIEW V_SPH_CARD_SALES
  COMMENT = 'SPH 카드매출 업종별 (서울 25구 467동, Marketplace 직접 참조)'
AS
SELECT
    PROVINCE_CODE, CITY_CODE, DISTRICT_CODE, STANDARD_YEAR_MONTH,
    CARD_TYPE, WEEKDAY_WEEKEND, GENDER, AGE_GROUP, TIME_SLOT, LIFESTYLE,
    FOOD_SALES, COFFEE_SALES, BEAUTY_SALES, MEDICAL_SALES,
    EDUCATION_ACADEMY_SALES, HOME_LIFE_SERVICE_SALES,
    TOTAL_SALES, TOTAL_COUNT
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.CARD_SALES_INFO;

-- Step 3: V_SPH_ASSET_INCOME — 자산소득 (269,159건)
CREATE OR REPLACE VIEW V_SPH_ASSET_INCOME
  COMMENT = 'SPH 자산소득 (서울 25구 467동, Marketplace 직접 참조)'
AS
SELECT
    PROVINCE_CODE, CITY_CODE, DISTRICT_CODE, STANDARD_YEAR_MONTH,
    GENDER, AGE_GROUP, CUSTOMER_COUNT,
    AVERAGE_INCOME, MEDIAN_INCOME, AVERAGE_HOUSEHOLD_INCOME,
    AVERAGE_ASSET_AMOUNT, RATE_HIGHEND,
    OWN_HOUSING_COUNT, MULTIPLE_HOUSING_COUNT,
    AVERAGE_PRICE_GAP, AVERAGE_LEASE_GAP
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.ASSET_INCOME_INFO;

-- Step 4: V_SPH_REGION_MASTER — 행정구역 마스터 (467건, DISTRICT_GEOM 포함)
CREATE OR REPLACE VIEW V_SPH_REGION_MASTER
  COMMENT = 'SPH 행정구역 마스터 (서울 25구 467동, GEOGRAPHY 포함, Marketplace 직접 참조)'
AS
SELECT
    PROVINCE_CODE, CITY_CODE, DISTRICT_CODE,
    PROVINCE_KOR_NAME, CITY_KOR_NAME, DISTRICT_KOR_NAME,
    PROVINCE_ENG_NAME, CITY_ENG_NAME, DISTRICT_ENG_NAME,
    DISTRICT_GEOM
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.M_SCCO_MST;
