-- ============================================================
-- 004_bjd_mapping.sql
-- BJD_CODE(법정동코드) ↔ DISTRICT_CODE(행정동코드) 매핑 뷰
-- 이슈: #20 (feat: BJD↔DISTRICT 매핑 뷰 생성)
-- 의존성: #17 (V_RICHGO_MARKET_PRICE), #18 (V_SPH_REGION_MASTER)
-- 멱등성: CREATE OR REPLACE — 반복 실행 안전
-- ============================================================

-- Step 0: 컨텍스트 설정
USE WAREHOUSE MOVING_INTEL_WH;
USE SCHEMA MOVING_INTEL.ANALYTICS;

-- Step 1: V_BJD_DISTRICT_MAP — 법정동코드 ↔ 행정동코드 매핑
-- 동 단위: LEFT(BJD_CODE, 8) = DISTRICT_CODE
-- 구 단위(끝4자리 0000): LEFT(BJD_CODE, 5) = CITY_CODE (fallback)
CREATE OR REPLACE VIEW V_BJD_DISTRICT_MAP
  COMMENT = 'RICHGO BJD_CODE(법정동 10자리) ↔ SPH DISTRICT_CODE(행정동 8자리) 매핑 뷰 (#20)'
AS
-- 동 단위 매핑 (BJD_CODE 끝4자리 != 0000)
SELECT
    m.PROVINCE_CODE,
    m.CITY_CODE,
    m.DISTRICT_CODE,
    m.DISTRICT_KOR_NAME,
    m.CITY_KOR_NAME,
    LEFT(r.BJD_CODE, 8) AS BJD_CODE_8,
    r.BJD_CODE,
    r.EMD AS RICHGO_EMD_NAME,
    'DONG' AS MATCH_LEVEL
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.M_SCCO_MST m
JOIN (
    SELECT DISTINCT BJD_CODE, EMD
    FROM MOVING_INTEL.ANALYTICS.V_RICHGO_MARKET_PRICE
    WHERE RIGHT(BJD_CODE, 4) != '0000'
) r ON LEFT(r.BJD_CODE, 8) = m.DISTRICT_CODE

UNION ALL

-- 구 단위 fallback 매핑 (BJD_CODE 끝4자리 = 0000)
SELECT DISTINCT
    m.PROVINCE_CODE,
    m.CITY_CODE,
    NULL AS DISTRICT_CODE,
    NULL AS DISTRICT_KOR_NAME,
    m.CITY_KOR_NAME,
    LEFT(r.BJD_CODE, 5) AS BJD_CODE_8,
    r.BJD_CODE,
    r.EMD AS RICHGO_EMD_NAME,
    'GU' AS MATCH_LEVEL
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.M_SCCO_MST m
JOIN (
    SELECT DISTINCT BJD_CODE, EMD
    FROM MOVING_INTEL.ANALYTICS.V_RICHGO_MARKET_PRICE
    WHERE RIGHT(BJD_CODE, 4) = '0000'
) r ON LEFT(r.BJD_CODE, 5) = m.CITY_CODE;
