-- ============================================================
-- 004_telecom_nexttrade_views.sql
-- 아정당 + NextTrade Marketplace 참조 뷰 6개 생성
-- 이슈: #19 (feat: 아정당 + NextTrade 참조 뷰 생성)
-- 의존성: #16 (MOVING_INTEL.ANALYTICS 스키마)
-- 멱등성: CREATE OR REPLACE — 반복 실행 안전
-- ============================================================

-- Step 0: 컨텍스트 설정
USE WAREHOUSE MOVING_INTEL_WH;
USE SCHEMA MOVING_INTEL.ANALYTICS;

-- ============================================================
-- 아정당 (SOUTH_KOREA_TELECOM_SUBSCRIPTION_ANALYTICS) 참조 뷰
-- ============================================================

-- Step 1: V_TELECOM_NEW_INSTALL — V05 신규 설치 (이사 시그널 핵심)
CREATE OR REPLACE VIEW V_TELECOM_NEW_INSTALL
  COMMENT = '아정당 신규설치 — 이사 시그널 핵심 (Marketplace 직접 참조)'
AS
SELECT
    YEAR_MONTH,
    INSTALL_STATE,
    INSTALL_CITY,
    CONTRACT_COUNT,
    OPEN_COUNT,
    PAYEND_COUNT,
    BUNDLE_COUNT,
    STANDALONE_COUNT,
    AVG_NET_SALES
FROM SOUTH_KOREA_TELECOM_SUBSCRIPTION_ANALYTICS__CONTRACTS_MARKETING_AND_CALL_CENTER_INSIGHTS_BY_REGION.TELECOM_INSIGHTS.V05_REGIONAL_NEW_INSTALL;

-- Step 2: V_TELECOM_CONTRACT_STATS — V01 월별 지역 계약통계
CREATE OR REPLACE VIEW V_TELECOM_CONTRACT_STATS
  COMMENT = '아정당 월별 지역 계약통계 (Marketplace 직접 참조)'
AS
SELECT
    YEAR_MONTH,
    INSTALL_STATE,
    INSTALL_CITY,
    MAIN_CATEGORY_NAME,
    CONTRACT_COUNT,
    CONSULT_REQUEST_COUNT,
    OPEN_COUNT,
    PAYEND_COUNT,
    OPEN_CVR,
    PAYEND_CVR,
    AVG_NET_SALES,
    TOTAL_NET_SALES
FROM SOUTH_KOREA_TELECOM_SUBSCRIPTION_ANALYTICS__CONTRACTS_MARKETING_AND_CALL_CENTER_INSIGHTS_BY_REGION.TELECOM_INSIGHTS.V01_MONTHLY_REGIONAL_CONTRACT_STATS;

-- Step 3: V_TELECOM_BUNDLE — V02 번들 패턴
CREATE OR REPLACE VIEW V_TELECOM_BUNDLE
  COMMENT = '아정당 번들 패턴 (Marketplace 직접 참조)'
AS
SELECT
    YEAR_MONTH,
    MAIN_CATEGORY_NAME,
    BUNDLE_COMBINATION,
    HAS_TV,
    HAS_PHONE,
    HAS_WIFI,
    CONTRACT_COUNT,
    PAYEND_COUNT,
    AVG_NET_SALES,
    AVG_POLICY_AMOUNT
FROM SOUTH_KOREA_TELECOM_SUBSCRIPTION_ANALYTICS__CONTRACTS_MARKETING_AND_CALL_CENTER_INSIGHTS_BY_REGION.TELECOM_INSIGHTS.V02_SERVICE_BUNDLE_PATTERNS;

-- Step 4: V_TELECOM_FUNNEL — V03 계약 퍼널
CREATE OR REPLACE VIEW V_TELECOM_FUNNEL
  COMMENT = '아정당 계약 퍼널 (Marketplace 직접 참조)'
AS
SELECT
    YEAR_MONTH,
    MAIN_CATEGORY_NAME,
    TOTAL_COUNT,
    CONSULT_REQUEST_COUNT,
    SUBSCRIPTION_COUNT,
    REGISTEND_COUNT,
    OPEN_COUNT,
    PAYEND_COUNT,
    CVR_CONSULT_REQUEST,
    CVR_SUBSCRIPTION,
    CVR_REGISTEND,
    CVR_OPEN,
    CVR_PAYEND,
    OVERALL_CVR
FROM SOUTH_KOREA_TELECOM_SUBSCRIPTION_ANALYTICS__CONTRACTS_MARKETING_AND_CALL_CENTER_INSIGHTS_BY_REGION.TELECOM_INSIGHTS.V03_CONTRACT_FUNNEL_CONVERSION;

-- ============================================================
-- NextTrade (NEXTRADE_EQUITY_MARKET_DATA) 참조 뷰
-- ============================================================

-- Step 5: V_NEXTTRADE_REFER — 종목 참조정보 (A0)
CREATE OR REPLACE VIEW V_NEXTTRADE_REFER
  COMMENT = 'NextTrade 종목 참조정보 (Marketplace 직접 참조)'
AS
SELECT
    DWDD,
    ISU_CD,
    ISU_SRT_CD,
    ISU_ABWD_NM,
    ISU_ENAW_NM,
    IND_ID,
    BASE_PRC,
    LSST_CT,
    CAPT_AMT
FROM NEXTRADE_EQUITY_MARKET_DATA.FIN.NX_HT_BAT_REFER_A0;

-- Step 6: V_NEXTTRADE_PRICE — 체결가 (A3) + 종목참조 JOIN
CREATE OR REPLACE VIEW V_NEXTTRADE_PRICE
  COMMENT = 'NextTrade 체결가 + 종목정보 (Marketplace 직접 참조)'
AS
SELECT
    p.DWDD,
    p.ISU_CD,
    r.ISU_ABWD_NM,
    r.IND_ID,
    p.TD_PRC,
    p.TRD_QTY,
    p.PRDY_CMP_PRC,
    p.OPPR,
    p.HGPR,
    p.LWPR,
    p.ACC_TRD_QTY,
    p.ACC_TRVAL
FROM NEXTRADE_EQUITY_MARKET_DATA.FIN.NX_HT_ONL_MKTPR_A3 p
JOIN NEXTRADE_EQUITY_MARKET_DATA.FIN.NX_HT_BAT_REFER_A0 r
    ON p.ISU_CD = r.ISU_CD AND p.DWDD = r.DWDD;
