-- ============================================================
-- test_06_integrated_mart.sql
-- MART_MOVE_ANALYSIS 통합 마트 검증 테스트 (TC-01 ~ TC-06)
-- 이슈: #21 (feat: 통합 마트 뷰 생성)
-- 실행 방법: 각 쿼리를 순서대로 실행하고 EXPECTED 주석과 비교
-- ============================================================

USE WAREHOUSE MOVING_INTEL_WH;
USE SCHEMA MOVING_INTEL.ANALYTICS;

-- TC-01: 마트 테이블 존재 + row count
SELECT COUNT(*) AS cnt FROM MOVING_INTEL.ANALYTICS.MART_MOVE_ANALYSIS;
-- EXPECTED: cnt > 0

-- TC-02: 25개 구 전체 커버
SELECT COUNT(DISTINCT CITY_CODE) AS gu_count FROM MOVING_INTEL.ANALYTICS.MART_MOVE_ANALYSIS;
-- EXPECTED: gu_count = 25

-- TC-03: 키 컬럼 NULL 확인
SELECT COUNT(*) AS null_keys FROM MOVING_INTEL.ANALYTICS.MART_MOVE_ANALYSIS
WHERE CITY_CODE IS NULL OR STANDARD_YEAR_MONTH IS NULL;
-- EXPECTED: null_keys = 0

-- TC-04: 필수 컬럼 존재 (MULTI_SOURCE 행)
SELECT CITY_CODE, STANDARD_YEAR_MONTH, OPEN_COUNT,
       TOTAL_RESIDENTIAL_POP, TOTAL_CARD_SALES, AVG_INCOME
FROM MOVING_INTEL.ANALYTICS.MART_MOVE_ANALYSIS
WHERE DATA_TIER = 'MULTI_SOURCE' LIMIT 1;
-- EXPECTED: 6개 컬럼 모두 NOT NULL

-- TC-04b: TELECOM_ONLY 행에서 OPEN_COUNT NOT NULL
SELECT COUNT(*) AS null_open FROM MOVING_INTEL.ANALYTICS.MART_MOVE_ANALYSIS
WHERE DATA_TIER = 'TELECOM_ONLY' AND OPEN_COUNT IS NULL;
-- EXPECTED: null_open = 0

-- TC-05: 월별 데이터 범위 (텔레콤 25구 완전 커버 spine 기준)
-- spine은 25개 구가 모두 텔레콤 데이터를 가진 월만 포함 (HAVING COUNT(DISTINCT CITY_CODE) = 25)
SELECT MIN(STANDARD_YEAR_MONTH) AS min_ym, MAX(STANDARD_YEAR_MONTH) AS max_ym
FROM MOVING_INTEL.ANALYTICS.MART_MOVE_ANALYSIS;
-- EXPECTED: min_ym = '202307', max_ym = '202604'

-- TC-06: DATA_TIER 분포
SELECT DATA_TIER, COUNT(DISTINCT CITY_CODE) AS gu_count
FROM MOVING_INTEL.ANALYTICS.MART_MOVE_ANALYSIS GROUP BY DATA_TIER;
-- EXPECTED: MULTI_SOURCE = 3, TELECOM_ONLY = 22
