-- ============================================================
-- test_15_district_profile.sql
-- 이슈 #43 — 3구 권역 프로파일 카드 데이터셋 검증 (TC-01 ~ TC-06)
-- 의존성: #21 머지 완료 (MART_MOVE_ANALYSIS, V_TELECOM_DISTRICT_MAPPED 등)
-- 멱등성: SELECT only (DDL 없음, 반복 실행 안전)
-- ============================================================

USE WAREHOUSE MOVING_INTEL_WH;
USE SCHEMA MOVING_INTEL.ANALYTICS;

-- TC-01: V_DISTRICT_PROFILE_3GU 존재 + 정확히 3행
SELECT COUNT(*) AS cnt FROM MOVING_INTEL.ANALYTICS.V_DISTRICT_PROFILE_3GU;
-- EXPECTED: cnt = 3

-- TC-02: 핵심 필드 NULL 없음 (CITY_CODE / AVG_INCOME / AVG_MEME_PRICE / OPEN_COUNT_MONTHLY_AVG)
SELECT COUNT(*) AS null_cnt
FROM MOVING_INTEL.ANALYTICS.V_DISTRICT_PROFILE_3GU
WHERE CITY_CODE IS NULL
   OR AVG_INCOME IS NULL
   OR AVG_MEME_PRICE IS NULL
   OR OPEN_COUNT_MONTHLY_AVG IS NULL;
-- EXPECTED: null_cnt = 0

-- TC-03: CITY_CODE 목록 정확히 일치 ('11140','11560','11650')
SELECT LISTAGG(CITY_CODE, ',') WITHIN GROUP (ORDER BY CITY_CODE) AS city_list
FROM MOVING_INTEL.ANALYTICS.V_DISTRICT_PROFILE_3GU;
-- EXPECTED: city_list = '11140,11560,11650'

-- TC-04: PROFILE_TAG 중복 없음 (3개 구 모두 고유 태그)
SELECT COUNT(DISTINCT PROFILE_TAG) AS tag_cnt
FROM MOVING_INTEL.ANALYTICS.V_DISTRICT_PROFILE_3GU;
-- EXPECTED: tag_cnt = 3

-- TC-05: 모든 행에서 AVG_MEME_PRICE > AVG_JEONSE_PRICE (매매가 > 전세가 상식 검증)
SELECT COUNT(*) AS violation_cnt
FROM MOVING_INTEL.ANALYTICS.V_DISTRICT_PROFILE_3GU
WHERE NOT (AVG_MEME_PRICE > AVG_JEONSE_PRICE);
-- EXPECTED: violation_cnt = 0

-- TC-06: GAP_RATIO 합리성 검증 (0 ~ 1 범위)
SELECT COUNT(*) AS out_of_range_cnt
FROM MOVING_INTEL.ANALYTICS.V_DISTRICT_PROFILE_3GU
WHERE GAP_RATIO NOT BETWEEN 0 AND 1;
-- EXPECTED: out_of_range_cnt = 0
