-- ============================================================
-- test_02_richgo_views.sql
-- RICHGO 뷰 3개 AC 검증 쿼리 (이슈 #17 AC 검증)
-- ============================================================

-- TC-01: 시세 뷰 존재 + row count
SELECT COUNT(*) AS cnt FROM MOVING_INTEL.ANALYTICS.V_RICHGO_MARKET_PRICE;
-- EXPECTED: cnt = 4356

-- TC-02: 시세 뷰 필수 컬럼 확인
SELECT REGION_LEVEL, BJD_CODE, SD, SGG, EMD, YYYYMMDD,
       TOTAL_HOUSEHOLDS, MEME_PRICE_PER_SUPPLY_PYEONG, JEONSE_PRICE_PER_SUPPLY_PYEONG
FROM MOVING_INTEL.ANALYTICS.V_RICHGO_MARKET_PRICE LIMIT 1;
-- EXPECTED: 9개 컬럼 모두 존재, 에러 없음

-- TC-03: 인구 뷰 존재 + row count
SELECT COUNT(*) AS cnt FROM MOVING_INTEL.ANALYTICS.V_RICHGO_POPULATION;
-- EXPECTED: cnt = 118

-- TC-04: 영유아 뷰 존재 + row count
SELECT COUNT(*) AS cnt FROM MOVING_INTEL.ANALYTICS.V_RICHGO_YOUNG_CHILDREN;
-- EXPECTED: cnt = 118

-- TC-05: 시세 뷰 날짜 범위 확인
SELECT MIN(YYYYMMDD) AS min_dt, MAX(YYYYMMDD) AS max_dt
FROM MOVING_INTEL.ANALYTICS.V_RICHGO_MARKET_PRICE;
-- EXPECTED: min_dt = 2012-01-01, max_dt = 2024-12-01

-- TC-06: 인구 뷰 필수 컬럼 확인
SELECT BJD_CODE, SD, SGG, EMD, YYYYMMDD,
       TOTAL, MALE, FEMALE,
       AGE_UNDER20, AGE_20S, AGE_30S, AGE_40S, AGE_50S, AGE_60S, AGE_OVER70
FROM MOVING_INTEL.ANALYTICS.V_RICHGO_POPULATION LIMIT 1;
-- EXPECTED: 15개 컬럼 모두 존재, 에러 없음

-- TC-07: 영유아 뷰 필수 컬럼 확인
SELECT BJD_CODE, SD, SGG, EMD, YYYYMMDD,
       AGE_UNDER5, FEMALE_20TO40, AGE_UNDER5_PER_FEMALE_20TO40
FROM MOVING_INTEL.ANALYTICS.V_RICHGO_YOUNG_CHILDREN LIMIT 1;
-- EXPECTED: 8개 컬럼 모두 존재, 에러 없음
